version: '{build}'

environment:
  matrix:
  - CONFIGURATION: Debug
  - CONFIGURATION: Release

install:
- ps: |
    # Hack to make WDK 1903 work on VS2015.
    # See https://github.com/appveyor-tests/WDK-10.0.14393.0/blob/31cf12217fe0c92b218c70d7027dfe145be4f4cb/appveyor.yml#L7
    [xml]$targets = get-content "C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.Common.targets"
    $usingTask = $targets.ChildNodes[1].UsingTask | ? {$_.TaskName -eq "ValidateNTTargetVersion"}
    $usingTask.AssemblyFile = '$(WDKContentRoot)build\bin\Microsoft.DriverKit.Build.Tasks.16.0.dll'
    $targets.Save("C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.Common.targets")
- appveyor AddMessage "Change boot configuration and reboot" -Category Information
- bcdedit /set testsigning on
- verifier /standard /driver winspd-x64.sys
- reg add HKLM\SYSTEM\CurrentControlSet\Control\StorPort\Verifier /v VerifyLevel /t REG_DWORD /d 1 /f
- if exist %SystemRoot%\memory.dmp del %SystemRoot%\memory.dmp
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 60

build_script:
- appveyor AddMessage "Reboot complete" -Category Information
- tools\build.bat %CONFIGURATION%

test_script:
- appveyor DownloadFile http://www.secfs.net/Test.Device.Storage.zip && 7z x Test.Device.Storage.zip
- appveyor DownloadFile http://www.secfs.net/TAEF.zip && 7z x TAEF.zip
- start /wait msiexec /i "Test.Device.Storage\HCK Device.Storage Content-x86_en-us.msi" /qn
- start /wait msiexec /i "TAEF\HCK TAEF Tools-x86_en-us.msi" /qn
- net stop shellhwdetection
- '"C:\Program Files (x86)\Windows Kits\10\bin\x64\certmgr.exe" /add /c build\VStudio\build\%CONFIGURATION%\winspd-x64.cer /s /r localMachine root'
- '"C:\Program Files (x86)\Windows Kits\10\bin\x64\certmgr.exe" /add /c build\VStudio\build\%CONFIGURATION%\winspd-x64.cer /s /r localMachine TrustedPublisher'
- '"C:\Program Files (x86)\Windows Kits\10\Tools\x64\devcon.exe" install build\VStudio\build\%CONFIGURATION%\winspd-x64.inf root\winspd'
- tools\run-tests.bat %CONFIGURATION%
- '"C:\Program Files (x86)\Windows Kits\10\Tools\x64\devcon.exe" remove root\winspd'
- if exist %SystemRoot%\memory.dmp exit 1

on_finish:
- if exist %SystemRoot%\memory.dmp (7z a memory.dmp.zip %SystemRoot%\memory.dmp && appveyor PushArtifact memory.dmp.zip)
- verifier /query
